import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter'
import { Box } from '@mui/material'
import './globals.css'

import '@fontsource/roboto/300.css'
import '@fontsource/roboto/400.css'
import '@fontsource/roboto/500.css'
import '@fontsource/roboto/700.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<AppRouterCacheProvider>
				<body
					className={inter.className}
					style={{
						display: 'flex',
						justifyContent: 'center',
						alignItems: 'center',
					}}
				>
					<Box
						sx={{
							p: 5,
							width: '70vw',
							maxWidth: 1100,
							minHeight: '50vh',
							maxHeight: 900,
							background: '#fff',
							borderRadius: 5,
							boxShadow: '0px 15px 30px rgba(0, 0, 0, 0.1)',
						}}
					>
						{children}
					</Box>
				</body>
			</AppRouterCacheProvider>
		</html>
	)
}
